AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Organization and Member Management

Parameters:
  Domain:
    Type: String
    Description: Domain associated tot his user pool
    
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Domain} Pool'

  SystemAdministratorsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: !Sub "System Administrators."
      GroupName: !Sub "SystemAdministrators"
      Precedence: 0
      UserPoolId: !Ref CognitoUserPool

Outputs:
  CognitoUserPool:
    Value: !Ref CognitoUserPool